# Generated by Django 5.1.2 on 2024-10-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leverweek', models.IntegerField()),
                ('oppot_week', models.IntegerField()),
                ('soort', models.CharField(max_length=100)),
                ('hoeveel_geen_water', models.IntegerField()),
                ('aantal_ziek_weggegooid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Potting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soort', models.CharField(max_length=100)),
                ('datum_van_check', models.DateField()),
                ('aantal_opgepot', models.IntegerField()),
                ('aantal_weggegooid', models.IntegerField()),
                ('werknemer', models.CharField(max_length=100)),
                ('reden_weg_gooi', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
