# Generated by Django 5.1.2 on 2024-10-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registratie_planten', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripsInfestationWeek10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('oppot_week', models.IntegerField()),
                ('lever_week', models.IntegerField()),
                ('aantal_tafels', models.IntegerField()),
                ('leverancier', models.CharField(max_length=100)),
                ('soort', models.CharField(max_length=100)),
                ('aantal_planten_weg_gooi', models.IntegerField()),
                ('aantal_planten_schade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TripsInfestationWijdezetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('oppot_week', models.IntegerField()),
                ('lever_week', models.IntegerField()),
                ('aantal_tafels', models.IntegerField()),
                ('leverancier', models.CharField(max_length=100)),
                ('soort', models.CharField(max_length=100)),
                ('aantal_planten_weg_gooi', models.IntegerField()),
                ('aantal_planten_schade', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='TripsInfestation',
        ),
    ]
