# Generated by Django 5.1.2 on 2024-10-17 14:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registratie_planten', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leverweek', models.IntegerField()),
                ('oppot_week', models.IntegerField()),
                ('soort', models.CharField(max_length=100)),
                ('hoeveel_geen_water', models.IntegerField()),
                ('aantal_ziek_weggegooid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Potting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soort', models.CharField(max_length=100)),
                ('datum_van_check', models.DateField()),
                ('aantal_opgepot', models.IntegerField()),
                ('aantal_weggegooid', models.IntegerField()),
                ('werknemer', models.CharField(max_length=100)),
                ('reden_weg_gooi', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leverancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
            ],
        ),

        migrations.AddField(
            model_name='potting',
            name='lever_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='potting',
            name='datum_van_check',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Soort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255, unique=True)),
                ('breeder_name', models.TextField(blank=True, null=True)),
                ('var_kleur', models.TextField(blank=True, null=True)),
                ('var_planthoogte', models.TextField(blank=True, null=True)),
                ('var_bloemgrootte', models.TextField(blank=True, null=True)),
                ('leverancier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registratie_planten.leverancier')),
            ],
        ),
        migrations.AlterField(
            model_name='diseasesearch',
            name='soort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registratie_planten.soort'),
        ),
        migrations.AlterField(
            model_name='potting',
            name='soort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registratie_planten.soort'),
        ),
        migrations.CreateModel(
            name='TripsInfestationWeek10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(default=django.utils.timezone.now)),
                ('oppot_week', models.IntegerField()),
                ('lever_week', models.IntegerField()),
                ('aantal_tafels', models.IntegerField()),
                ('aantal_planten_weg_gooi', models.IntegerField()),
                ('aantal_planten_schade', models.IntegerField()),
                ('soort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registratie_planten.soort')),
            ],
        ),
        migrations.CreateModel(
            name='TripsInfestationWijdezetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(default=django.utils.timezone.now)),
                ('oppot_week', models.IntegerField()),
                ('lever_week', models.IntegerField()),
                ('aantal_tafels', models.IntegerField()),
                ('aantal_planten_weg_gooi', models.IntegerField()),
                ('aantal_planten_schade', models.IntegerField()),
                ('soort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registratie_planten.soort')),
            ],
        ),
        migrations.CreateModel(
            name='PlantenInfoWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_nummer', models.IntegerField(default=1)),
                ('var_bladlengte', models.TextField(blank=True, null=True)),
                ('var_vertakkingen', models.TextField(blank=True, null=True)),
                ('var_wortel', models.TextField(blank=True, null=True)),
                ('var_1_spike', models.TextField(blank=True, null=True)),
                ('var_2_spike', models.TextField(blank=True, null=True)),
                ('var_3_spike', models.TextField(blank=True, null=True)),
                ('var_potmaat', models.TextField(blank=True, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registratie_planten.soort')),
            ],
            options={
                'unique_together': {('name', 'week_nummer')},
            },
        ),
    ]
