# Generated by Django 5.1.2 on 2024-10-17 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registratie_planten', '0002_leverancier_potting_lever_week_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseasesearch',
            name='oppot_week',
        ),
    ]
