# Generated by Django 5.1.2 on 2024-10-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registratie_planten', '0003_remove_diseasesearch_oppot_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripsinfestationweek10',
            name='oppot_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripsinfestationwijdezetting',
            name='oppot_week',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
